/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityQuestionsRouteImport } from './routes/security-questions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpSupportRouteImport } from './routes/help-support'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DataRouteImport } from './routes/data'
import { Route as ConnectRouterRouteImport } from './routes/connect-router'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AirtimeRouteImport } from './routes/airtime'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddPaymentMethodRouteImport } from './routes/add-payment-method'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityQuestionsRoute = SecurityQuestionsRouteImport.update({
  id: '/security-questions',
  path: '/security-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRouterRoute = ConnectRouterRouteImport.update({
  id: '/connect-router',
  path: '/connect-router',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AirtimeRoute = AirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPaymentMethodRoute = AddPaymentMethodRouteImport.update({
  id: '/add-payment-method',
  path: '/add-payment-method',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-payment-method': typeof AddPaymentMethodRoute
  '/admin': typeof AdminRouteWithChildren
  '/airtime': typeof AirtimeRoute
  '/change-password': typeof ChangePasswordRoute
  '/connect-router': typeof ConnectRouterRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topup': typeof TopupRoute
  '/tv': typeof TvRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-payment-method': typeof AddPaymentMethodRoute
  '/airtime': typeof AirtimeRoute
  '/change-password': typeof ChangePasswordRoute
  '/connect-router': typeof ConnectRouterRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topup': typeof TopupRoute
  '/tv': typeof TvRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-payment-method': typeof AddPaymentMethodRoute
  '/admin': typeof AdminRouteWithChildren
  '/airtime': typeof AirtimeRoute
  '/change-password': typeof ChangePasswordRoute
  '/connect-router': typeof ConnectRouterRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topup': typeof TopupRoute
  '/tv': typeof TvRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-payment-method'
    | '/admin'
    | '/airtime'
    | '/change-password'
    | '/connect-router'
    | '/data'
    | '/devices'
    | '/help-support'
    | '/history'
    | '/login'
    | '/map'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/topup'
    | '/tv'
    | '/admin/analytics'
    | '/admin/broadcasts'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-payment-method'
    | '/airtime'
    | '/change-password'
    | '/connect-router'
    | '/data'
    | '/devices'
    | '/help-support'
    | '/history'
    | '/login'
    | '/map'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/topup'
    | '/tv'
    | '/admin/analytics'
    | '/admin/broadcasts'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/add-payment-method'
    | '/admin'
    | '/airtime'
    | '/change-password'
    | '/connect-router'
    | '/data'
    | '/devices'
    | '/help-support'
    | '/history'
    | '/login'
    | '/map'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/security-questions'
    | '/settings'
    | '/signup'
    | '/topup'
    | '/tv'
    | '/admin/analytics'
    | '/admin/broadcasts'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPaymentMethodRoute: typeof AddPaymentMethodRoute
  AdminRoute: typeof AdminRouteWithChildren
  AirtimeRoute: typeof AirtimeRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConnectRouterRoute: typeof ConnectRouterRoute
  DataRoute: typeof DataRoute
  DevicesRoute: typeof DevicesRoute
  HelpSupportRoute: typeof HelpSupportRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SecurityQuestionsRoute: typeof SecurityQuestionsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TopupRoute: typeof TopupRoute
  TvRoute: typeof TvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-questions': {
      id: '/security-questions'
      path: '/security-questions'
      fullPath: '/security-questions'
      preLoaderRoute: typeof SecurityQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-support': {
      id: '/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-router': {
      id: '/connect-router'
      path: '/connect-router'
      fullPath: '/connect-router'
      preLoaderRoute: typeof ConnectRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airtime': {
      id: '/airtime'
      path: '/airtime'
      fullPath: '/airtime'
      preLoaderRoute: typeof AirtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-payment-method': {
      id: '/add-payment-method'
      path: '/add-payment-method'
      fullPath: '/add-payment-method'
      preLoaderRoute: typeof AddPaymentMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPaymentMethodRoute: AddPaymentMethodRoute,
  AdminRoute: AdminRouteWithChildren,
  AirtimeRoute: AirtimeRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConnectRouterRoute: ConnectRouterRoute,
  DataRoute: DataRoute,
  DevicesRoute: DevicesRoute,
  HelpSupportRoute: HelpSupportRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SecurityQuestionsRoute: SecurityQuestionsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TopupRoute: TopupRoute,
  TvRoute: TvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
